<?php

function dc_custom_form_settings_menu() {
/*** Menu link to update user fields to confirm real name via dialog-box, dialog-box created in page.tpl files ***/
  $items['dc_custom_form_user_real_name_confirmation/%'] = array(
    'title' => 'Real Name Confirmation',
    'page callback' => 'user_real_name_confirmation',
    'page arguments' => array(1),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );  
  return $items;
}

function user_real_name_confirmation($confirmation_value){
    // $confirmation_value = 1 means user got the update message.
    // $confirmation_value = 2 reminder user the alert message on other day.
    global $user;
    if($user->uid != 0){
        $user_details = user_load($user->uid);
        if(isset($confirmation_value) && $confirmation_value ==1){            
            $user_details->field_confirmed_realname['und'][0]['value'] = 1; 
            user_save($user_details);
            drupal_goto($base_url.'/user/'.$user->uid.'/edit');            
        }
        if(isset($confirmation_value) && $confirmation_value ==2){ 
            $tomorrow = date("Y-m-d", strtotime("+ 1 day"));
            $user_details->field_confirmed_realname['und'][0]['value'] = $tomorrow;    
            user_save($user_details);
            drupal_goto($base_url.'/user');            
        }
    }else{
        drupal_set_message('You are not authorized to access this page.','error');
        drupal_goto($base_url);        
    }
}



function dc_custom_form_settings_form_alter(&$form, &$form_state, $form_id){
    //print "<pre>"; print_r($form); die();
    if($form['#id'] == 'views-exposed-form-new-wishlists-page-1'){
        if (isset($form['name'])) {
                $form['name']['#attributes'] = array('placeholder' => array(t('search wishlists...')));
        }
    }
    
    if($form_id == 'user_profile_form'){
   	$form['field_delivery_address']['und']['0']['phone_block']['phone_number']['phone_number']['#required'] = TRUE;
    }
    
    if($form_id == 'user_register_form'){
   	$form['field_delivery_address']['und']['0']['phone_block']['phone_number']['phone_number']['#required'] = TRUE;
    }    
    
    if($form['#id'] == 'commerce-checkout-form-review'){
        //print "<pre>"; print_r($form); die();
        if(isset($form['commerce_payment']['payment_details']['credit_card']['owner'])){
            $form['commerce_payment']['payment_details']['credit_card']['owner']['#title'] = 'Your name on card';
            $form['commerce_payment']['payment_details']['credit_card']['code']['#title'] = 'Security code / CVC';
        }
        if($form['commerce_payment']['payment_method']['#default_value']== 'commerce_no_payment|commerce_payment_commerce_no_payment'){
          // unset($form['customer_profile_billing']);
        }
        
        if(isset($form['customer_profile_billing'])){
            $form['customer_profile_billing']['commerce_customer_address']['und'][0]['locality_block']['postal_code']['#title'] = 'Postcode / ZIP Code';
        }
        //$form['buttons']['continue']['#value'] = 'Complete order';
    }
    
    if($form['#id'] == 'commerce-checkout-form-checkout'){
        $form['account']['login']['mail']['#title'] = 'Purchasers email';
    }
    
}

function dc_custom_form_settings_commerce_checkout_pane_info_alter(&$checkout_pane) {

  global $user;
  $order = commerce_cart_order_load($user->uid);
  if (!empty($order)) {

    //get the order wrapper and order total
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
    $order_total = $order_wrapper->commerce_order_total->amount->value();

    // hide payment and billing info if the order total is <= 0
    if ((int) $order_total <= 0) {
      $checkout_pane['customer_profile_billing']['enabled'] = FALSE;
    }
  }
}

function dc_custom_form_settings_commerce_payment_order_paid_in_full($order, $transaction){
    global $base_url;
//  print "<pre>"; print_r($order);
//  print "<pre>"; print_r($transaction); die();
            
    if(isset($order->commerce_line_items['und'][0]['line_item_id']) && $transaction->status == 'success'){
            $line_item_id = $order->commerce_line_items['und'][0]['line_item_id'];
            $line_items = commerce_line_item_load($line_item_id);        
        if($line_items->line_item_label != 'dc_gift_voucher'){
            $order_id = $order->order_id;
            $user_id = $line_items->field_wish_list_owner_ref['und'][0]['target_id'];  
            $user_details = user_load($user_id);
            
            if(isset($order->field_gift_message_txt['und'][0]['value'])){            
                $gift_message = $order->field_gift_message_txt['und'][0]['value'];
                $complete_gift_message = '<br/>There is a message attached to your gift:<br/><br/>'.$gift_message;
            }else{
                $complete_gift_message = '';
            }
            
	$key = 'dc_custom_form_settings_email';
	$to = $user_details->mail;
	$from = 'DeliveryCode <support@deliverycode.com>';
	$params = array(
    'body' => '<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td bgcolor="#FFFFFF" style="border-collapse: collapse;" valign="top"><!--[if (gte mso 9)|(IE)]><table width="600" align="center" cellpadding="0" cellspacing="0" border="0">
	<tr><td><![endif]-->	<table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" class="content" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;max-width: 600px;width: 100%;">
	<tbody><tr><td align="center" bgcolor="#000000" style="border-collapse: collapse;" valign="top"><span style="color: #ffffff; font-family: Arial; font-size: 11px; text-align: center;">To ensure you receive our emails, please add support@deliverycode.com to your address book or safe list </span></td>
	</tr><tr><td style="padding: 10px 10px 10px 10px;border-collapse: collapse;" valign="top"><!--[if (gte mso 9)|(IE)]><table width="438" align="left" cellpadding="0" cellspacing="0" border="0">
	<tr><td><![endif]--><!-- Start Header--><table align="center" border="0" cellpadding="0" cellspacing="0" class="deviceWidth" width="580"><tbody><tr>
	<td bgcolor="#ffffff" width="100%"><!-- Logo --><table align="left" border="0" cellpadding="0" cellspacing="0" class="deviceWidth"><tbody><tr>
	<td class="center" style="padding:10px 20px"><a href="#"><img alt="" border="0" src="http://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/29cd4659-94ad-4b7c-aee4-8459ac94a2f9.jpg" />
	</a></td></tr></tbody></table><!-- End Logo --><table align="left" border="0" cellpadding="0" cellspacing="0" class="deviceWidth"><tbody><tr>
	<td class="center" style="padding: 30px 0 0 30px"><a href="#"><img alt="DeliveryCode available on the App Store" src="https://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/adde9ea1-f675-4a49-b4fb-517ccae6f418.jpg" />
	</a></td></tr></tbody></table><!-- Nav --><table align="right" border="0" cellpadding="0" cellspacing="0" class="deviceWidth"><tbody><tr><td class="center" style="font-size: 12px; color: #000000; font-weight: bold; text-align: right; font-family: Arial; line-height: 20px; vertical-align: middle; padding:40px 10px 20px; font-style:bold">
	<a href="'.$base_url.'" style="text-decoration: none; color: #000000;">Home</a> &nbsp;&nbsp;&nbsp; <a href="'.$base_url.'/how-it-works" style="text-decoration: none; color: #000000;">How it Works</a>
	&nbsp;&nbsp;&nbsp; <a href="'.$base_url.'/user" style="text-decoration: none; color: #000000;">My Account</a></td></tr></tbody></table><!-- End Header -->
	<!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]--></td></tr><tr><td style="border-collapse: collapse;" valign="top">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td style="border-collapse: collapse;" valign="top"><table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td align="center" style="border-collapse: collapse;max-width: 487px;width: 100%;background:#000000;" valign="top">
	<p style="mso-table-lspace:0;mso-table-rspace:0; margin:0"><br /><br /><span style="color: #FFFFFF; font-family: Arial; font-size: 25px; line-height: 16px; font-weight:bold; padding: 0 0 10px 0;">
	PURCHASED ITEM</span><br /><br />&nbsp;</p></td></tr><tr><td style="height: 10px;border-collapse: collapse;" valign="top">&nbsp;</td></tr><tr>
	<td style="border-collapse: collapse;" valign="top"><!--[if (gte mso 9)|(IE)]><table width="600" align="right" cellpadding="0" cellspacing="0" border="0" style="border: 1px solid #ffffff;">
	<tr><td><![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" class="main-text" style="border: 1px solid #ffffff;width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
	<tbody><tr><td style="width: 20px;border-collapse: collapse;" valign="top">&nbsp;</td><td style="border-collapse: collapse;" valign="top">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td style="border-collapse: collapse;" valign="top"><!--[if (gte mso 9)|(IE)]><table width="580" align="right" cellpadding="0" cellspacing="0" border="0" style="border: 1px solid #ffffff;">
	<tr><td><![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" class="main-text" style="border: 1px solid #ffffff;width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
	<tbody><tr><td style="border-collapse: collapse;" valign="top"><p style="mso-table-lspace:0;mso-table-rspace:0; margin:0"><br />
	<span style="color: #000000; font-family: Arial; font-size: 13px; line-height: 16px; padding: 0 0 10px 0;">Dear '.ucfirst($user_details->name).'<br />
	<br />An item on your wishlist has been purchased under order number: '.$order_id.'. <a href="'.$base_url.'/user/login" target="_blank">Login</a> to see which one..<br/><br/>Delivery Code are processing this order and will let you know once this item has been shipped.<br/>'.$complete_gift_message.'</span></p></td></tr><tr>
	<td style="height: 10px;border-collapse: collapse;" valign="top">&nbsp;</td></tr><tr>
	<td align="center" style="border-collapse: collapse;" valign="top"><a alt="Open Site" href="'.$base_url.'">
	<img align="middle" alt="Open Site" class="fwimage" src="http://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/35798292-f9d9-4aff-a679-6f17c68d04c3.jpg" style="display: block;max-width: 398px;width: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto;" /></a></td>
	</tr><tr><td style="height: 10px;border-collapse: collapse;" valign="top">&nbsp;</td></tr><tr><td style="border-collapse: collapse;" valign="top">
	<p style="mso-table-lspace:0;mso-table-rspace:0; margin:0"><span style="color: #000000; font-family: Arial; font-size: 13px; line-height: 16px; padding: 0 0 10px 0; font-weight:bold;">
	- DeliveryCode team</span></p></td></tr></tbody></table><!--[if (gte mso 9)|(IE)]> </td></tr></table><![endif]--></td></tr></tbody></table></td>
	<td style="width: 20px;border-collapse: collapse;" valign="top">&nbsp;</td></tr></tbody></table><!--[if (gte mso 9)|(IE)]> </td></tr></table><![endif]-->
	</td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td style="padding: 10px 10px 10px 10px;border-collapse: collapse;" valign="top">
	<!--[if (gte mso 9)|(IE)]><table width="580" align="left" cellpadding="0" cellspacing="0" border="0"><tr><td><![endif]--><!-- Start Header-->
	<table align="center" border="0" cellpadding="0" cellspacing="0" class="deviceWidth" width="580"><tbody><tr><td bgcolor="#ffffff" width="100%">
	<!-- Social --><table align="right" border="0" cellpadding="0" cellspacing="0" class="deviceWidth"><tbody><tr>
	<td class="center" style="font-size: 12px; color: #000000; font-weight: bold; text-align: right; font-family: Arial; line-height: 20px; vertical-align: middle; padding:10px 20px; font-style:bold" width="30">
	<a href="http://www.facebook.com/deliverycode" style="text-decoration: none;"><img align="left" class="fwimage" src="http://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/01ab8850-b625-41f9-a138-86f72bccfc01.jpg" style="display: block;max-width: 31px;width: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto;padding-right:20px;" />
	</a></td><td class="center" style="font-size: 12px; color: #000000; font-weight: bold; text-align: right; font-family: Arial; line-height: 20px; vertical-align: middle; padding:10px 20px; font-style:bold" width="30">
	<a href="http://twitter.com/delivery_code" style="text-decoration: none;"><img align="left" class="fwimage" src="http://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/4ae8f912-7c8e-4a40-b507-631e8c3ae188.jpg" style="display: block;max-width: 31px;width: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto;padding-right:20px;" />
	</a></td></tr></tbody></table><!-- End Nav --></td></tr></tbody></table><!-- End Header --><!--[if (gte mso 9)|(IE)]> </td></tr></table><![endif]-->
	</td></tr><tr></tr></tbody></table><table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td align="center" bgcolor="#000000" style="border-collapse: collapse; padding: 5px 0;" valign="top">
	<span style="color: #ffffff; font-family: Arial; font-size: 11px;"><a href="'.$base_url.'/contact-us" style="text-decoration: none; color: #ffffff;">
	Contact Us</a> &nbsp;/&nbsp;<a href="'.$base_url.'/privacy" style="text-decoration: none; color: #ffffff;">Privacy</a> &nbsp;/&nbsp;<a href="'.$base_url.'/terms" style="text-decoration: none; color: #ffffff;">
	Terms and Conditions</a> </span><br/></td></tr><tr><!-- <td valign="top"  bgcolor="#000000" align="center" style="border-collapse: collapse;">
	<span style="color: #666666; font-family: Arial; font-size: 11px;"><br></td></tr> --></tr><tr>
	<td align="center" style="color: #000; font-family: Arial; font-size: 11px;"><br />Copyright © 2014 Delivery Code. All rights reserved.<br />
	<br />We reserve the right to change the Terms &amp; Conditions at any time<br />
	If you no longer wish to receive emails from Delivery Code, please unsubscribe by clicking 
	<a href="file:///tmp/dc_backup.html#" style="color: #666666;" target="_blank">here</a><br />
	Unless otherwise noted, Delivery Code has applied VAT at 20% to the appropriate items in this transaction based on country of delivery in accordance with the EU laws on distance selling. Our VAT number is GB 180725703<br />
	This email was sent to you by Delivery Code, Registered number: 8662491. Registered Address: Terleys, Molehill Green, Felsted, Dunmow, Essex CM6 3JP
	</td></tr><tr><td height="60" style="border-collapse: collapse;" valign="top">&nbsp;</td></tr></tbody></table></td></tr></tbody></table>
	<!--[if (gte mso 9)|(IE)]> </td></tr></table><![endif]--></td></tr></tbody></table><p>&nbsp;</p>',
    'subject' => 'PURCHASED ITEM',
    ); 
	$mail = drupal_mail('dc_custom_form_settings', $key, $to, language_default(), $params, $from);            
            
        }
    }

   // print "<pre>"; print_r($order->field_gift_message_txt['und'][0]['value']); 
   //    die();
}

function dc_custom_form_settings_mail($key, &$message, $params) {

  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8;',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal'
  );

  foreach ($headers as $key => $value) {
    $message['headers'][$key] = $value;
  }

  $message['subject'] = $params['subject'];
  $message['body'] = $params['body'];
}


/*** Delete user's wishlist when user deleted via admin ****/
function dc_custom_form_settings_user_delete($account) {
     db_query('DELETE FROM wishlist WHERE uid ='.$account->uid);
}

?>