<?php

function dc_custom_form_settings_form_alter(&$form, &$form_state, $form_id){
    //print "<pre>"; print_r($form); die();
    if($form['#id'] == 'views-exposed-form-new-wishlists-page-1'){
        if (isset($form['name'])) {
                $form['name']['#attributes'] = array('placeholder' => array(t('search wishlists...')));
        }
    }
    
    if($form_id == 'user_profile_form'){
   	$form['field_delivery_address']['und']['0']['phone_block']['phone_number']['phone_number']['#required'] = TRUE;
    }
    
    if($form_id == 'user_register_form'){
   	$form['field_delivery_address']['und']['0']['phone_block']['phone_number']['phone_number']['#required'] = TRUE;
    }    
    
    if($form['#id'] == 'commerce-checkout-form-review'){
        //print "<pre>"; print_r($form); die();
        if(isset($form['commerce_payment']['payment_details']['credit_card']['owner'])){
            $form['commerce_payment']['payment_details']['credit_card']['owner']['#title'] = 'Your name on card';
            $form['commerce_payment']['payment_details']['credit_card']['code']['#title'] = 'Security code / CVC';
        }
        if($form['commerce_payment']['payment_method']['#default_value']== 'commerce_no_payment|commerce_payment_commerce_no_payment'){
          // unset($form['customer_profile_billing']);
        }
        
        if(isset($form['customer_profile_billing'])){
            $form['customer_profile_billing']['commerce_customer_address']['und'][0]['locality_block']['postal_code']['#title'] = 'Postcode / ZIP Code';
        }
        $form['buttons']['continue']['#value'] = 'Complete order';
    }
    
    if($form['#id'] == 'commerce-checkout-form-checkout'){
        $form['account']['login']['mail']['#title'] = 'Purchasers email';
    }
    
}

function dc_custom_form_settings_commerce_checkout_pane_info_alter(&$checkout_pane) {

  global $user;
  $order = commerce_cart_order_load($user->uid);
  if (!empty($order)) {

    //get the order wrapper and order total
    $order_wrapper = entity_metadata_wrapper('commerce_order', $order);
    $order_total = $order_wrapper->commerce_order_total->amount->value();

    // hide payment and billing info if the order total is <= 0
    if ((int) $order_total <= 0) {
      $checkout_pane['customer_profile_billing']['enabled'] = FALSE;
    }
  }
}
?>