<?php

function hd_theme_alterations_form_alter(&$form, &$form_state, $form_id){
  if($form_id == "views_exposed_form"){
    $form['title']['#attributes'] = array('placeholder' => array(t('Enter keyword here')));
  }
  if ($form_id == "user_register_form") {
    $form['actions']['submit']['#attributes']['class'][] = 'col-md-6 register-btn';
  }
  if ($form_id == "webform_client_form_7") {
  $form['actions']['submit']['#value'] = '<span class="bg-sprite bg-sprite-tick">Submit</span>';
   $form['actions']['submit']['#attributes']['class'] = array('col-xs-12', 'col-md-6', 'col-md-offset-3', 'contact-btn');
  }



}

function hd_theme_alterations_preprocess_page(&$vars) {
// Front page does not need text under title
  if (($vars['is_front']) != 'TRUE') {
// Theming for the news pages
    if ((isset($vars['node'])) && (($vars['node']->type) == 'news')) {
      $node = $vars['node'];
      $vars['theme_hook_suggestions'][] = 'page__'. $vars['node']->type;
// Don't set empty variable
      if (!empty($node->field_text_under_title)) {
        $vars['title2'] = $node->field_text_under_title[LANGUAGE_NONE][0]['safe_value'];
      }
    }
    if ((isset($vars['node'])) && (($vars['node']->type) == 'page')) {
      $node = $vars['node'];
// Don't set empty variable
      if (!empty($node->field_text_under_title)) {
        $vars['title2'] = $node->field_text_under_title[LANGUAGE_NONE][0]['safe_value'];
      }
    }
  }
 if(!empty($vars['user'])) {
      if (drupal_match_path(current_path(),"user") ||
          drupal_match_path(current_path(),"user/*")){
          menu_set_active_item('user');
      }
  }
  //hide hybridauth
  if(isset($vars['page']['content']['system_main']['hybridauth_identities'])){
    unset($vars['page']['content']['system_main']['hybridauth_identities']);
  }
  //hide login forms on registration page
  if(drupal_match_path(current_path(),"create-a-wishlist")||
    isset($vars['page']['content']['user_login'])){
      unset($vars['page']['content']['user_login']);
      unset($vars['page']['content']['system_main']['#prefix']);
  }
}

function hd_theme_alterations_preprocess_node(&$vars) {
// Pass webform to node 8
    if ((isset($vars['nid'])) && ($vars['nid'] == '8')) {
    $node = node_load(9);
    webform_node_view($node, 'full');
    $vars['webform'] = theme_webform_view($node->content);
  }

}

function hd_theme_alterations_block_view_alter(&$data, $block) {
  if ($block->bid == '158') {
    $data['content'] = _cards_block_content();
  }

}

//html content for the cards block
function _cards_block_content(){
  global $user;
  //load the user to get their wishlist
  $current_user = user_load($user->uid);

  if($user->uid != 0){
    $wishlist_link = '<p><a class="btn-create-wishlist" href="'.$wishlist_url.'"><span class="bg-sprite bg-sprite-ico-star">View my Wishlist</span></a></p>';
  }else{
    $wishlist_link = '<p><a class="btn-create-wishlist" href="/user"><span class="bg-sprite bg-sprite-ico-star">Create a Wishlist</span></a></p>';
  }
  $output = $wishlist_link;
  $output.='<div class="payment-methods">
  <p>We accept all of the following payment methods:</p>
  <img alt="" class="payment-methods-img" src="/sites/all/themes/hiddendelivery/images/HomePage/payment-methods.jpg" />
  <ul class="visually-hidden payment-list">
    <li class="visa">
      Visa</li>
    <li class="amex">
      American Express</li>
    <li class="diners-club">
      Diners Club</li>
    <li class="mastercard">
      Mastercard</li>
    <li class="jcb">
      JCB</li>
    <li>
      ???</li>
    <li class="giropay">
      GiroPay</li>
    <li class="paypal">
      Paypal</li>
    <li class="bitcoin">
      Bitcoin</li>
  </ul>
</div>';
  return $output;
}
