<?php

function hd_theme_alterations_form_alter(&$form, &$form_state, $form_id){
  if($form_id == "views_exposed_form"){
    $form['title']['#attributes'] = array('placeholder' => array(t('Enter keyword here')));
  }
  if ($form_id == "user_register_form") {
    $form['actions']['submit']['#attributes']['class'][] = 'col-md-6 register-btn';
  }
  if ($form_id == "webform_client_form_7") {
  $form['actions']['submit']['#value'] = '<span class="bg-sprite bg-sprite-tick">Submit</span>';
   $form['actions']['submit']['#attributes']['class'] = array('col-xs-12', 'col-md-6', 'col-md-offset-3', 'contact-btn');
  }



}

function hd_theme_alterations_preprocess_page(&$vars) {
//dpm($vars);
// Front page does not need text under title
  if (($vars['is_front']) != 'TRUE') {
// Theming for the news pages
    if ((isset($vars['node'])) && (($vars['node']->type) == 'news')) {
      $node = $vars['node'];
      $vars['theme_hook_suggestions'][] = 'page__'. $vars['node']->type;
// Don't set empty variable
      if (!empty($node->field_text_under_title)) {
        $vars['title2'] = $node->field_text_under_title[LANGUAGE_NONE][0]['safe_value'];
      }
    }
    if ((isset($vars['node'])) && (($vars['node']->type) == 'page')) {
      $node = $vars['node'];
// Don't set empty variable
      if (!empty($node->field_text_under_title)) {
        $vars['title2'] = $node->field_text_under_title[LANGUAGE_NONE][0]['safe_value'];
      }
    }
  }
 if(!empty($vars['user'])) {
      if (drupal_match_path(current_path(),"user") ||
          drupal_match_path(current_path(),"user/*")){
          menu_set_active_item('user');
      }
  }
  //hide hybridauth
  if(isset($vars['page']['content']['system_main']['hybridauth_identities'])){
    unset($vars['page']['content']['system_main']['hybridauth_identities']);
  }
  //hide login forms on registration page
  if(drupal_match_path(current_path(),"create-a-wishlist")||
    isset($vars['page']['content']['user_login'])){
      unset($vars['page']['content']['user_login']);
      unset($vars['page']['content']['system_main']['#prefix']);
  }
  //hide shiiping info as we do need it
  if (isset($vars['page']['content']['system_main']['commerce_customer_shipping'])){
    unset($vars['page']['content']['system_main']['commerce_customer_shipping']);
  }
  // print checkout progress
  if(arg(0) == 'checkout'){
    $checkout_progress_block = block_load('commerce_checkout_progress', 'indication');
    $checkout_progress_block = _block_get_renderable_array(_block_render_blocks(array($checkout_progress_block)));
    $vars['checkout_progress_block'] = drupal_render($checkout_progress_block);
  }
}

function hd_theme_alterations_preprocess_node(&$vars) {
// Pass webform to node 8
    if ((isset($vars['nid'])) && ($vars['nid'] == '8')) {
    $node = node_load(9);
    webform_node_view($node, 'full');
    $vars['webform'] = theme_webform_view($node->content);
  }

}

function hd_theme_alterations_block_view_alter(&$data, $block) {
  global $user;
  global $base_url;
  //set cards block content
  if (isset($block->bid)&&$block->bid == '158') {
    $data['content'] = _cards_block_content();
  }
  //redirect link for the wishlist
  if (isset($block->bid)&&$block->bid == '110') {
    $current_user = user_load($user->uid);
    $wishlist_url = str_replace("http://www.deliverycode.com", "",
      $current_user->field_profile_wishlist_url[LANGUAGE_NONE][0]['value']);
    //wishlist link
    $data['content']['#content'][864]['#href'] = $base_url.$wishlist_url;
    //edit wishlist link
    $data['content']['#content'][3212]['#href'] = $base_url.$wishlist_url.'/edit';
  }

}

//html content for the cards block
function _cards_block_content(){
  global $user;
  global $base_url;
  //load the user to get their wishlist
  $current_user = user_load($user->uid);
  if($current_user->uid != 0){
  $wishlist_url = str_replace("http://www.deliverycode.com", "",
      $current_user->field_profile_wishlist_url[LANGUAGE_NONE][0]['value']);
  //print view my wishlist link
  $wishlist_link = '<p><a class="btn-create-wishlist" href="'.$wishlist_url.'"><span class="bg-sprite bg-sprite-ico-star">View my wishlist</span></a></p>';
  }else{
    // print create my wishlist link
    $wishlist_link = '<p><a class="btn-create-wishlist" href="/create-a-wishlist"><span class="bg-sprite bg-sprite-ico-star">Create a wishlist</span></a></p>';
  }
  $output = $wishlist_link;
  $output.='<div class="payment-methods">
  <span>We accept all of the following payment methods:</span>
  <img alt="" class="payment-methods-img" src="'.$base_url.'/sites/all/themes/hiddendelivery/images/HomePage/payment-methods.jpg" /></div>';
  return $output;
}
