<?php

global $user;

function dc_vote_form_alter(&$form, &$form_state, $form_id) {
    if($form['#id'] == 'views-exposed-form-new-wishlists-page-1'){
        if (isset($form['name'])) {
                $form['name']['#attributes'] = array('placeholder' => array(t('search wishlists...')));
        }
    }
    
   $user_ip = ip_address();
   if($form_id == 'dc_vote_node_form' && $form['nid']['#value'] == ''){  
       $userWishlistId = arg(1);
      	hide($form['title']);
        hide($form['receiver_user_id_vote']);
        hide($form['wishlist_id_vote']); 
        hide($form['user_ip_vote']);
       $form['title']['#default_value'] = 'Vote to '.$userWishlistId; 
       $form['wishlist_id_vote']['und'][0]['value']['#default_value'] = $userWishlistId;
	   $form['user_ip_vote']['und'][0]['value']['#default_value'] = $user_ip;
       $getUserId = db_query("SELECT uid FROM wishlist WHERE wishlist_id ='".$userWishlistId."'");
       foreach($getUserId AS $wishlistUser){
           $userId = $wishlistUser->uid;
       }
       $form['receiver_user_id_vote']['und'][0]['value']['#default_value'] = $userId;
       $form['actions']['submit']['#value'] = 'Click here to <span class="vote-me-text">Vote</span> for me';
       unset($form['actions']['preview']);
       
   }else if($form_id == 'user_profile_form'){
   		$form['field_delivery_address']['und']['0']['phone_block']['phone_number']['phone_number']['#required'] = TRUE;
   }else if($form_id == 'user_register_form'){
   		$form['field_delivery_address']['und']['0']['phone_block']['phone_number']['phone_number']['#required'] = TRUE;
   }
}
function dc_vote_node_submit($node, $form, &$form_state) {
	//print $form['#form_id']; die();
	if($form['#form_id'] == 'dc_vote_node_form'){
	    if($node->type == 'dc_vote' && $node->nid == ''){
	    	
	        $VoteModelId = $node->wishlist_id_vote['und'][0]['value'];
			$user_id = $node->receiver_user_id_vote['und'][0]['value'];
	
			//print "<pre>"; print_r(user_load($user_id)); die();
			$select_currency_rates_nid = db_query("SELECT nid FROM node WHERE type ='currency_exchange_rates_for_gift' ORDER BY nid ASC LIMIT 1");
			foreach($select_currency_rates_nid AS $res_currency_rates){
				$currency_rates_nid = $res_currency_rates->nid;
			}        

			$load_user_id = user_load($user_id);
			if(isset($load_user_id->field_promotion_model['und']['0']['value']) && $load_user_id->field_promotion_model['und']['0']['value'] == 1){
				$vote_price = db_query("SELECT field_dc_promotional_voting_pric_value FROM field_data_field_dc_promotional_voting_pric WHERE entity_id ='".$currency_rates_nid."'");
					foreach($vote_price AS $res_vote_price){
						$votePrice = $res_vote_price->field_dc_promotional_voting_pric_value;
					}				
			}else{
				$vote_price = db_query("SELECT field_dc_voting_price_value FROM field_data_field_dc_voting_price WHERE entity_id ='".$currency_rates_nid."'");
					foreach($vote_price AS $res_vote_price){
						$votePrice = $res_vote_price->field_dc_voting_price_value;
					}				
			}
			
			$select_user_balace = db_query('SELECT field_gift_balance_usd_value FROM field_data_field_gift_balance_usd WHERE entity_id ='.$user_id);
			foreach($select_user_balace AS $res_balance){
				$usd_balance = $res_balance->field_gift_balance_usd_value;
			}
			
	    	$user_ip = ip_address(); 
	    	$vote_status = db_query("SELECT n.nid FROM field_data_wishlist_id_vote AS w LEFT JOIN field_data_user_ip_vote AS v ON v.entity_id = w.entity_id LEFT JOIN node AS n on n.nid = w.entity_id WHERE v.user_ip_vote_value='".$user_ip."' AND w.wishlist_id_vote_value ='".$VoteModelId."'");
			foreach($vote_status AS $res_vote_status){
				$vote_done = $res_vote_status->nid;
			}
			
			if($vote_done != ''){
				drupal_set_message('You can not vote muliple times to the same model.', 'error');
				drupal_goto('wishlist/'.$VoteModelId);
				
			}		
			else{
				if($usd_balance == ''){
					
					$total_user_balance = number_format($votePrice, 2);
					db_query("INSERT INTO field_data_field_gift_balance_usd (entity_type, bundle, deleted, entity_id, revision_id, language, delta, field_gift_balance_usd_value, field_gift_balance_usd_format) VALUES ('user', 'user', 0, '".$user_id."', '".$user_id."', 'und', 0, '".$total_user_balance."', 'NULL')");
					field_cache_clear(TRUE);
					
					node_save($node);
					drupal_goto('wishlist/'.$VoteModelId);
				}else{
					$total_user_balance = number_format(($usd_balance + $votePrice), 2);
					
						db_update('field_data_field_gift_balance_usd')
						->fields(array('field_gift_balance_usd_value' => $total_user_balance))
					    ->condition('entity_id', $user_id)
					    ->execute();
						field_cache_clear(TRUE);	
							
					node_save($node);
					
			        drupal_goto('wishlist/'.$VoteModelId);
				}
			}
	    } 
    } 
}
?>