<?php
drupal_session_start();  
global $user;

function dc_gift_vouchers_form_alter(&$form, &$form_state, $form_id) {
    //print "<pre>"; print_r($form); die('hii');
   if($form_id == 'dc_gift_vouchers_node_form' && $form['nid']['#value'] == ''){  
       //print "<pre>"; print_r($form); die();
       $userWishlistId = arg(1);
       $form['select_currency_gift_voucher']['#weight'] = -1;
       $form['select_amount_gift_voucher']['#weight'] = 0;
       $form['title']['#weight'] = 1;
       $form['your_message_gift_voucher']['#weight'] = 2;

       $form['select_amount_gift_voucher']['und']['#default_value'] = 10;
       $form['select_currency_gift_voucher']['und']['#default_value'] ="USD";
      
        hide($form['receiver_user_id_gift_voucher']);
        hide($form['wishlist_id_gift_voucher']); 
        hide($form['order_id_gift_voucher']);
		hide($form['order_status_gift_voucher']);
		hide($form['username_gift_voucher']);
        
       $form['wishlist_id_gift_voucher']['und'][0]['value']['#default_value'] = $userWishlistId;
       $getUserId = db_query("SELECT uid FROM wishlist WHERE wishlist_id ='".$userWishlistId."'");
       foreach($getUserId AS $wishlistUser){
           $userId = $wishlistUser->uid;
		   
       }

       $getUserName = db_query("SELECT name FROM users WHERE uid ='".$userId."'");
       foreach($getUserName AS $resGetUserName){
           $userName = $resGetUserName->name;
		   
       }	   
	   
       $form['receiver_user_id_gift_voucher']['und'][0]['value']['#default_value'] = $userId;
	   $form['username_gift_voucher']['und'][0]['value']['#default_value'] = $userName;
	   $form['order_id_gift_voucher']['und'][0]['value']['#default_value'] = 0;
	   $form['order_status_gift_voucher']['und'][0]['value']['#default_value'] = 0;
       $form['actions']['submit']['#value'] = 'Send';
       unset($form['actions']['preview']);
       
   }
}
function dc_gift_vouchers_node_submit($node, $form, &$form_state) {
	//print "<pre>"; print_r($form); die();
	if($form['#form_id'] == 'dc_gift_vouchers_node_form'){
		if($node->type == 'dc_gift_vouchers' && $node->nid == ''){
			//die('hi');
	        node_save($node);
			$_SESSION['gift_voucher_nid'] = $node->nid;
	        $product = commerce_product_load_by_sku('dc_gift_voucher');
	        commerce_cart_product_add_by_id($product->product_id);
	        drupal_goto('cart');		
		}
	}
 
}


function dc_gift_vouchers_commerce_cart_line_item_refresh($line_item, $order_wrapper){ 
   // print "<pre>"; print_r($line_item->order_id); die();
    if ($line_item->line_item_label == 'dc_gift_voucher') {
    	
			if(isset($_SESSION['gift_voucher_nid']) && $_SESSION['gift_voucher_nid'] != ''){
			$user_node_del = '';
			$select_user_bal_node = db_query('SELECT entity_id FROM field_data_order_id_user_bal_update WHERE order_id_user_bal_update_value ='.$line_item->order_id);
			foreach($select_user_bal_node AS $res_user_bal_node){
				 $user_node_del = $res_user_bal_node->entity_id;
			}
			if($user_node_del != ''){
				node_delete($user_node_del);
			}
			
							
					db_update('field_data_order_id_gift_voucher')
					->fields(array('order_id_gift_voucher_value' => 0))
				    ->condition('order_id_gift_voucher_value', $line_item->order_id)
				    ->execute();
				
							
					db_update('field_data_order_id_gift_voucher')
					->fields(array('order_id_gift_voucher_value' => $line_item->order_id))
				    ->condition('entity_id', $_SESSION['gift_voucher_nid'])
				    ->execute();			
					unset($_SESSION['gift_voucher_nid']);
				}
				
				field_cache_clear(TRUE);		
		
		
    	$gv_node = '';

			$select_gv_node = db_query('SELECT entity_id FROM field_data_order_id_gift_voucher WHERE order_id_gift_voucher_value ='.$line_item->order_id);
			foreach($select_gv_node AS $res_gv_node){
				 $gv_node = $res_gv_node->entity_id;
			}			
			$node = node_load($gv_node);
			//print "<pre>"; print_r($node); die('hi');


			$gift_voucher_value = $node->select_amount_gift_voucher['und'][0]['value'];
			$gift_voucher_currency = $node->select_currency_gift_voucher['und'][0]['value'];		

        $price = 100 * $gift_voucher_value; //1 dollar
        $currency_rates_nid = '';
		$select_currency_rates_nid = db_query("SELECT nid FROM node WHERE type ='currency_exchange_rates_for_gift' ORDER BY nid ASC LIMIT 1");
		foreach($select_currency_rates_nid AS $res_currency_rates){
			$currency_rates_nid = $res_currency_rates->nid;
		}
        
        if($gift_voucher_value < 25){
        	
        	$giftVoucherRate = db_query("SELECT field_dc_fee_25_value AS rate FROM field_data_field_dc_fee_25 WHERE entity_id='".$currency_rates_nid."'");
			
        }elseif($gift_voucher_value >= 25 && $gift_voucher_value < 50){
        	
        	$giftVoucherRate = db_query("SELECT field_dc_fee_25_00_49_99_value AS rate FROM field_data_field_dc_fee_25_00_49_99 WHERE entity_id='".$currency_rates_nid."'");

        }elseif($gift_voucher_value >= 50 && $gift_voucher_value < 100){
        	
        	$giftVoucherRate = db_query("SELECT field_dc_fee_50_00_99_99_value AS rate FROM field_data_field_dc_fee_50_00_99_99 WHERE entity_id='".$currency_rates_nid."'");

        }elseif($gift_voucher_value >= 100){
        	
        	$giftVoucherRate = db_query("SELECT field_dc_fee_100__value AS rate FROM field_data_field_dc_fee_100_ WHERE entity_id='".$currency_rates_nid."'");

        }
    	$giftRate = '';
	       foreach($giftVoucherRate AS $resGiftVoucherRate){
	           $giftRate = $resGiftVoucherRate->rate;
	       }
		   
		$rate = $giftRate;        
        $fee = ($gift_voucher_value * $rate) / 100;
        $deliveryCodeFee = $fee * 100;
        $line_item->commerce_unit_price[LANGUAGE_NONE]['0']['amount']=$price;
        $line_item->commerce_unit_price[LANGUAGE_NONE]['0']['currency_code']=$gift_voucher_currency;
        //alter the base_price component
        $line_item->commerce_unit_price[LANGUAGE_NONE]['0']['data']['components']['0']['price']['amount']=$price;
        $line_item->commerce_unit_price[LANGUAGE_NONE]['0']['data']['components']['0']['price']['currency_code']=$gift_voucher_currency;        
        $line_item->commerce_unit_price[LANGUAGE_NONE]['0']['data']['components']['1']['price']['amount']=$deliveryCodeFee;
        $line_item->commerce_unit_price[LANGUAGE_NONE]['0']['data']['components']['1']['price']['currency_code']=$gift_voucher_currency;
        
        //unset($_SESSION['gift_voucher_value']);
    }

}



function dc_gift_vouchers_commerce_checkout_pane_info_alter(&$checkout_pane) {
	//print "<pre>"; print_r($checkout_pane); die();
    $order_id = arg(1);
	$productType = '';
    $getProductType = db_query("SELECT line_item_label  FROM commerce_line_item WHERE  order_id='".$order_id."'");
       foreach($getProductType AS $resProductType){
           $productType = $resProductType->line_item_label;
       }
       if($productType == 'dc_gift_voucher'){ 
//            unset($checkout_pane['customer_profile_billing']);
            unset($checkout_pane['commerce_shipping']);
			unset($checkout_pane['commerce_fieldgroup_pane__group_gift_message']);

       }
}

function dc_gift_vouchers_commerce_payment_order_paid_in_full($order, $transaction) {
global $user;
global $base_url;

		if($transaction->status == 'success'){
		
			$select_order_type = db_query('SELECT line_item_label FROM commerce_line_item WHERE order_id ='.$transaction->order_id);
			foreach($select_order_type AS $res_order_type){
				$order_type = $res_order_type->line_item_label;
			}
			
			$select_currency_rates_nid = db_query("SELECT nid FROM node WHERE type ='currency_exchange_rates_for_gift' ORDER BY nid ASC LIMIT 1");
			foreach($select_currency_rates_nid AS $res_currency_rates){
				$currency_rates_nid = $res_currency_rates->nid;
			}
				
		//print $order_type; die();		
		if($order_type == 'dc_gift_voucher'){
			
                    
                    
                    
                    $select_gv_node = db_query('SELECT entity_id FROM field_data_order_id_gift_voucher WHERE order_id_gift_voucher_value ='.$transaction->order_id);
			foreach($select_gv_node AS $res_gv_node){
				 $gv_node = $res_gv_node->entity_id;
			}			
			$node = node_load($gv_node);
			//print "<pre>"; print_r($node); die('hi');

			$sender_name = $node->title;
			$gift_message = $node->your_message_gift_voucher['und'][0]['value'];
			$user_id = $node->receiver_user_id_gift_voucher['und'][0]['value'];
			$amount = $node->select_amount_gift_voucher['und'][0]['value'];
			$currency = $node->select_currency_gift_voucher['und'][0]['value'];
			
			$select_user_balace = db_query('SELECT field_gift_balance_usd_value FROM field_data_field_gift_balance_usd WHERE entity_id ='.$user_id);
			foreach($select_user_balace AS $res_balance){
				$usd_balance = $res_balance->field_gift_balance_usd_value;
			}
			if($usd_balance == ''){
				
				if($currency == 'USD'){
					
					$user_balance = $amount;			
					
				}else if($currency == 'GBP'){
					
					$usd_vs_gbp = db_query("SELECT field__1_gbp_value FROM field_data_field__1_gbp WHERE entity_id ='".$currency_rates_nid."'");
					foreach($usd_vs_gbp AS $res_usd_vs_gbp){
						$gbp_rate = $res_usd_vs_gbp->field__1_gbp_value;
					}
									
					$amount_usd = number_format(($amount / $gbp_rate), 2);
					$user_balance = $amount_usd;
					
				}else if($currency == 'EUR'){
					
					$usd_vs_eur = db_query("SELECT field__1_eur_value FROM field_data_field__1_eur WHERE entity_id ='".$currency_rates_nid."'");
					foreach($usd_vs_eur AS $res_usd_vs_eur){
						$eur_rate = $res_usd_vs_eur->field__1_eur_value;
					}
					
					$amount_eur = number_format(($amount / $eur_rate), 2);
					$user_balance =  $amount_eur;
					
				}				
				//$user_balance = number_format(($user_balance), 2);
				db_query("INSERT INTO field_data_field_gift_balance_usd (entity_type, bundle, deleted, entity_id, revision_id, language, delta, field_gift_balance_usd_value, field_gift_balance_usd_format) VALUES ('user', 'user', 0, '".$user_id."', '".$user_id."', 'und', 0, '".$user_balance."', 'NULL')");
				
				
				field_cache_clear(TRUE);
				
			}else{
				
				if($currency == 'USD'){
					                                       
					$user_balance = $usd_balance + $amount;
                        
					
				}else if($currency == 'GBP'){
					
					$usd_vs_gbp = db_query("SELECT field__1_gbp_value FROM field_data_field__1_gbp WHERE entity_id ='".$currency_rates_nid."'");
					foreach($usd_vs_gbp AS $res_usd_vs_gbp){
						$gbp_rate = $res_usd_vs_gbp->field__1_gbp_value;
					}
									
					$amount_usd = number_format(($amount / $gbp_rate), 2);
					$user_balance = $usd_balance + $amount_usd;
					
				}else if($currency == 'EUR'){
					
					$usd_vs_eur = db_query("SELECT field__1_eur_value FROM field_data_field__1_eur WHERE entity_id ='".$currency_rates_nid."'");
					foreach($usd_vs_eur AS $res_usd_vs_eur){
						$eur_rate = $res_usd_vs_eur->field__1_eur_value;
					}
					
					$amount_eur = number_format(($amount / $eur_rate), 2);
					$user_balance = $usd_balance + $amount_eur;
					
				}
				 //$user_balance = number_format(($user_balance), 2); 
				db_update('field_data_field_gift_balance_usd')
				->fields(array('field_gift_balance_usd_value' => $user_balance))
			    ->condition('entity_id', $user_id)
			    ->execute();
				
								
				field_cache_clear(TRUE);			
			}
			db_update('field_data_order_status_gift_voucher')
				->fields(array('order_status_gift_voucher_value' => 1))
			    ->condition('entity_id', $node->nid)
			    ->execute();
				
			$email_user = user_load($user_id);
			if($currency == 'USD'){
				$currency_sign = '$';
			}else if($currency == 'GBP'){
				$currency_sign = '£';
			}else if($currency == 'EUR'){
				$currency_sign = '€';
			}
	$key = 'dc_gift_vouchers_email';
	$to = $email_user->mail;
	$from = 'DeliveryCode <support@deliverycode.com>';
	$params = array(
    'body' => '<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td bgcolor="#FFFFFF" style="border-collapse: collapse;" valign="top"><!--[if (gte mso 9)|(IE)]><table width="600" align="center" cellpadding="0" cellspacing="0" border="0">
	<tr><td><![endif]-->	<table align="center" bgcolor="#ffffff" border="0" cellpadding="0" cellspacing="0" class="content" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;max-width: 600px;width: 100%;">
	<tbody><tr><td align="center" bgcolor="#000000" style="border-collapse: collapse;" valign="top"><span style="color: #ffffff; font-family: Arial; font-size: 11px; text-align: center;">To ensure you receive our emails, please add support@deliverycode.com to your address book or safe list </span></td>
	</tr><tr><td style="padding: 10px 10px 10px 10px;border-collapse: collapse;" valign="top"><!--[if (gte mso 9)|(IE)]><table width="438" align="left" cellpadding="0" cellspacing="0" border="0">
	<tr><td><![endif]--><!-- Start Header--><table align="center" border="0" cellpadding="0" cellspacing="0" class="deviceWidth" width="580"><tbody><tr>
	<td bgcolor="#ffffff" width="100%"><!-- Logo --><table align="left" border="0" cellpadding="0" cellspacing="0" class="deviceWidth"><tbody><tr>
	<td class="center" style="padding:10px 20px"><a href="#"><img alt="" border="0" src="http://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/29cd4659-94ad-4b7c-aee4-8459ac94a2f9.jpg" />
	</a></td></tr></tbody></table><!-- End Logo --><table align="left" border="0" cellpadding="0" cellspacing="0" class="deviceWidth"><tbody><tr>
	<td class="center" style="padding: 30px 0 0 30px"><a href="#"><img alt="DeliveryCode available on the App Store" src="https://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/adde9ea1-f675-4a49-b4fb-517ccae6f418.jpg" />
	</a></td></tr></tbody></table><!-- Nav --><table align="right" border="0" cellpadding="0" cellspacing="0" class="deviceWidth"><tbody><tr><td class="center" style="font-size: 12px; color: #000000; font-weight: bold; text-align: right; font-family: Arial; line-height: 20px; vertical-align: middle; padding:40px 10px 20px; font-style:bold">
	<a href="'.$base_url.'" style="text-decoration: none; color: #000000;">Home</a> &nbsp;&nbsp;&nbsp; <a href="'.$base_url.'/how-it-works" style="text-decoration: none; color: #000000;">How it Works</a>
	&nbsp;&nbsp;&nbsp; <a href="'.$base_url.'/user" style="text-decoration: none; color: #000000;">My Account</a></td></tr></tbody></table><!-- End Header -->
	<!--[if (gte mso 9)|(IE)]></td></tr></table><![endif]--></td></tr><tr><td style="border-collapse: collapse;" valign="top">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td style="border-collapse: collapse;" valign="top"><table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td align="center" style="border-collapse: collapse;max-width: 487px;width: 100%;background:#000000;" valign="top">
	<p style="mso-table-lspace:0;mso-table-rspace:0; margin:0"><br /><br /><span style="color: #FFFFFF; font-family: Arial; font-size: 25px; line-height: 16px; font-weight:bold; padding: 0 0 10px 0;">
	Gift Voucher</span><br /><br />&nbsp;</p></td></tr><tr><td style="height: 10px;border-collapse: collapse;" valign="top">&nbsp;</td></tr><tr>
	<td style="border-collapse: collapse;" valign="top"><!--[if (gte mso 9)|(IE)]><table width="600" align="right" cellpadding="0" cellspacing="0" border="0" style="border: 1px solid #ffffff;">
	<tr><td><![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" class="main-text" style="border: 1px solid #ffffff;width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
	<tbody><tr><td style="width: 20px;border-collapse: collapse;" valign="top">&nbsp;</td><td style="border-collapse: collapse;" valign="top">
	<table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td style="border-collapse: collapse;" valign="top"><!--[if (gte mso 9)|(IE)]><table width="580" align="right" cellpadding="0" cellspacing="0" border="0" style="border: 1px solid #ffffff;">
	<tr><td><![endif]--><table align="left" border="0" cellpadding="0" cellspacing="0" class="main-text" style="border: 1px solid #ffffff;width: 100%;border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;">
	<tbody><tr><td style="border-collapse: collapse;" valign="top"><p style="mso-table-lspace:0;mso-table-rspace:0; margin:0"><br />
	<span style="color: #000000; font-family: Arial; font-size: 13px; line-height: 16px; padding: 0 0 10px 0;">Dear '.ucfirst($email_user->name).'<br />
	<br />You have received a '.$currency_sign.''.$amount.' gift voucher!<br/><br/>Customer Name: '.ucfirst($sender_name).'<br/><br/>
	The customer wrote the following gift message:<br/>'.$gift_message.'</span></p></td></tr><tr>
	<td style="height: 10px;border-collapse: collapse;" valign="top">&nbsp;</td></tr><tr><td style="border-collapse: collapse;" valign="top">
	<p style="mso-table-lspace:0;mso-table-rspace:0; margin:0"><span style="color: #000000; font-family: Arial; font-size: 13px; line-height: 16px; padding: 0 0 10px 0;">
	Login to <a href="'.$base_url.'" target="_blank">www.deliverycode.com</a> to spend your voucher or add more products to your wishlist.</span></p></td></tr><tr>
	<td style="height: 10px;border-collapse: collapse;" valign="top">&nbsp;</td></tr><tr>
	<td align="center" style="border-collapse: collapse;" valign="top"><a alt="Open Site" href="'.$base_url.'">
	<img align="middle" alt="Open Site" class="fwimage" src="http://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/35798292-f9d9-4aff-a679-6f17c68d04c3.jpg" style="display: block;max-width: 398px;width: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto;" /></a></td>
	</tr><tr><td style="height: 10px;border-collapse: collapse;" valign="top">&nbsp;</td></tr><tr><td style="border-collapse: collapse;" valign="top">
	<p style="mso-table-lspace:0;mso-table-rspace:0; margin:0"><span style="color: #000000; font-family: Arial; font-size: 13px; line-height: 16px; padding: 0 0 10px 0; font-weight:bold;">
	- DeliveryCode team</span></p></td></tr></tbody></table><!--[if (gte mso 9)|(IE)]> </td></tr></table><![endif]--></td></tr></tbody></table></td>
	<td style="width: 20px;border-collapse: collapse;" valign="top">&nbsp;</td></tr></tbody></table><!--[if (gte mso 9)|(IE)]> </td></tr></table><![endif]-->
	</td></tr></tbody></table></td></tr></tbody></table></td></tr><tr><td style="padding: 10px 10px 10px 10px;border-collapse: collapse;" valign="top">
	<!--[if (gte mso 9)|(IE)]><table width="580" align="left" cellpadding="0" cellspacing="0" border="0"><tr><td><![endif]--><!-- Start Header-->
	<table align="center" border="0" cellpadding="0" cellspacing="0" class="deviceWidth" width="580"><tbody><tr><td bgcolor="#ffffff" width="100%">
	<!-- Social --><table align="right" border="0" cellpadding="0" cellspacing="0" class="deviceWidth"><tbody><tr>
	<td class="center" style="font-size: 12px; color: #000000; font-weight: bold; text-align: right; font-family: Arial; line-height: 20px; vertical-align: middle; padding:10px 20px; font-style:bold" width="30">
	<a href="http://www.facebook.com/deliverycode" style="text-decoration: none;"><img align="left" class="fwimage" src="http://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/01ab8850-b625-41f9-a138-86f72bccfc01.jpg" style="display: block;max-width: 31px;width: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto;padding-right:20px;" />
	</a></td><td class="center" style="font-size: 12px; color: #000000; font-weight: bold; text-align: right; font-family: Arial; line-height: 20px; vertical-align: middle; padding:10px 20px; font-style:bold" width="30">
	<a href="http://twitter.com/delivery_code" style="text-decoration: none;"><img align="left" class="fwimage" src="http://gallery.mailchimp.com/be5f319b883fe2a2b83f96a61/images/4ae8f912-7c8e-4a40-b507-631e8c3ae188.jpg" style="display: block;max-width: 31px;width: 100%;outline: none;text-decoration: none;-ms-interpolation-mode: bicubic;height: auto;padding-right:20px;" />
	</a></td></tr></tbody></table><!-- End Nav --></td></tr></tbody></table><!-- End Header --><!--[if (gte mso 9)|(IE)]> </td></tr></table><![endif]-->
	</td></tr><tr></tr></tbody></table><table align="center" border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse;mso-table-lspace: 0pt;mso-table-rspace: 0pt;" width="100%">
	<tbody><tr><td align="center" bgcolor="#000000" style="border-collapse: collapse; padding: 5px 0;" valign="top">
	<span style="color: #ffffff; font-family: Arial; font-size: 11px;"><a href="'.$base_url.'/contact-us" style="text-decoration: none; color: #ffffff;">
	Contact Us</a> &nbsp;/&nbsp;<a href="'.$base_url.'/privacy" style="text-decoration: none; color: #ffffff;">Privacy</a> &nbsp;/&nbsp;<a href="'.$base_url.'/terms" style="text-decoration: none; color: #ffffff;">
	Terms and Conditions</a> </span><br/></td></tr><tr><!-- <td valign="top"  bgcolor="#000000" align="center" style="border-collapse: collapse;">
	<span style="color: #666666; font-family: Arial; font-size: 11px;"><br></td></tr> --></tr><tr>
	<td align="center" style="color: #000; font-family: Arial; font-size: 11px;"><br />Copyright © 2014 Delivery Code. All rights reserved.<br />
	<br />We reserve the right to change the Terms &amp; Conditions at any time<br />
	If you no longer wish to receive emails from Delivery Code, please unsubscribe by clicking 
	<a href="file:///tmp/dc_backup.html#" style="color: #666666;" target="_blank">here</a><br />
	Unless otherwise noted, Delivery Code has applied VAT at 20% to the appropriate items in this transaction based on country of delivery in accordance with the EU laws on distance selling. Our VAT number is GB 180725703<br />
	This email was sent to you by Delivery Code, Registered number: 8662491. Registered Address: Terleys, Molehill Green, Felsted, Dunmow, Essex CM6 3JP
	</td></tr><tr><td height="60" style="border-collapse: collapse;" valign="top">&nbsp;</td></tr></tbody></table></td></tr></tbody></table>
	<!--[if (gte mso 9)|(IE)]> </td></tr></table><![endif]--></td></tr></tbody></table><p>&nbsp;</p>',
    'subject' => 'New gift voucher for you',
    );
	$mail = drupal_mail('dc_gift_vouchers', $key, $to, language_default(), $params, $from);				
			
					
			
		}

		
	}
}


function dc_gift_vouchers_mail($key, &$message, $params) {

  $headers = array(
    'MIME-Version' => '1.0',
    'Content-Type' => 'text/html; charset=UTF-8;',
    'Content-Transfer-Encoding' => '8Bit',
    'X-Mailer' => 'Drupal'
  );

  foreach ($headers as $key => $value) {
    $message['headers'][$key] = $value;
  }

  $message['subject'] = $params['subject'];
  $message['body'] = $params['body'];
}

?>
