<?php

/**
 * @file
 * Services hook for the definition of custom services.
 */

function hd_endpoint_services_resources() {
  $resource['wishlist']['actions'] = array(
    'retrieve' => array(
      'help' => 'Retrieve wishlists for a user.',
      'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/wishlist'),
      'callback' => '_wishlist_resource_view',
      'access callback' => 'services_access_menu',
      //'access arguments' => array('update'),
      //'access arguments append' => TRUE,
      'args' => array(
        array(
          'name' => 'uid',
          'optional' => FALSE,
          'source' => array('data' => 'uid'),
          'type' => 'int',
          'description' => 'The wishlist owners uid.',
        ),
      ),
    ),
    'create' => array(
      'help' => 'Create a wishlist for a user.',
      'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/wishlist'),
      'callback' => '_wishlist_resource_create',
      'access callback' => 'services_access_menu',
      //'access arguments' => array('update'),
      //'access arguments append' => TRUE,
      'args' => array(
        array(
          'name' => 'wishlist_name',
          'optional' => FALSE,
          'source' => array('data' => 'wishlist_name'),
          'type' => 'string',
          'description' => 'The wishlist name.',
        ),
      ),
    ),
    'add_product' => array(
      'help' => 'Add a product to a users wishlist.',
      'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/wishlist'),
      'callback' => '_wishlist_resource_add_product',
      'access callback' => 'services_access_menu',
      //'access arguments' => array('update'),
      //'access arguments append' => TRUE,
      'args' => array(
        array(
          'name' => 'wishlist_id',
          'optional' => FALSE,
          'source' => array('data' => 'wishlist_id'),
          'type' => 'int',
          'description' => 'The wishlist id.',
        ),
        array(
          'name' => 'product_url',
          'optional' => FALSE,
          'source' => array('data' => 'product_url'),
          'type' => 'string',
          'description' => 'The URL of the product to add the wishlist.',
        ),
      ),
    ),
  );

  return $resource;
}



