<?php
/**
 * @file
 * Services hook for the definition of custom services.
 */

function hd_endpoint_services_resources() {
  $resource['wishlist']['actions'] = array(
    'retrieve' => array(
      'help' => 'Retrieve wishlists for a user.',
      'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/wishlist'),
      'callback' => '_wishlist_resource_view',
      'access callback' => 'services_access_menu',
      //'access arguments' => array('update'),
      //'access arguments append' => TRUE,
      'args' => array(
        array(
          'name' => 'uid',
          'optional' => FALSE,
          'source' => array('data' => 'uid'),
          'type' => 'int',
          'description' => 'The wishlist owners uid.',
        ),
      ),
    ),
    'create' => array(
      'help' => 'Create a wishlist for a user.',
      'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/wishlist'),
      'callback' => '_wishlist_resource_create',
      'access callback' => 'services_access_menu',
      //'access arguments' => array('update'),
      //'access arguments append' => TRUE,
      'args' => array(
        array(
          'name' => 'wishlist_name',
          'optional' => FALSE,
          'source' => array('data' => 'wishlist_name'),
          'type' => 'string',
          'description' => 'The wishlist name.',
        ),
      ),
    ),
    'add_product' => array(
      'help' => 'Add a product to a users wishlist.',
      'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/wishlist'),
      'callback' => '_wishlist_resource_add_product',
      'access callback' => 'services_access_menu',
      //'access arguments' => array('update'),
      //'access arguments append' => TRUE,
      'args' => array(
        array(
              'name' => 'uid',
              'optional' => TRUE,
              'type' => 'int',
              'description' => 'The user id.',
              'default value' => 0,
              'source' => array('param' => 'uid'),
        ),
        array(
              'name' => 'wishlist_id',
              'optional' => TRUE,
              'type' => 'int',
              'description' => 'The wishlist id.',
              'default value' => 0,
              'source' => array('param' => 'wishlist_id'),
        ),
        array(
              'name' => 'product_url',
              'optional' => TRUE,
              'type' => 'string',
              'description' => 'The product url.',
              'default value' => 0,
              'source' => array('param' => 'product_url'),
        ),
      ),
    ),
  );
$resource['dc_user'] = array(
  'update' => array(
          'help' => 'Update a user',
          'callback' => '_hd_user_update_resource',
          'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/user'),
          'access callback' => 'services_access_menu',
          'access arguments' => array('update'),
          'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'uid',
              'type' => 'int',
              'description' => 'Unique identifier for this user',
              'source' => array('path' => 0),
              'optional' => FALSE,
            ),
            array(
              'name' => 'data',
              'type' => 'array',
              'description' => 'The user object with updated information',
              'source' => 'data',
              'optional' => FALSE,
            ),
          ),
        ),
  'create' => array(
          'help' => 'Create a user',
          'callback' => '_hd_user_resource_create',
          'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/user'),
          'access callback' => 'services_access_menu',
          'access arguments' => array('create'),
          'access arguments append' => FALSE,
          'args' => array(
            array(
              'name' => 'account',
              'type' => 'array',
              'description' => 'The user object',
              'source' => 'data',
              'optional' => FALSE,
            ),
          ),
        ),
  );

$resource['dc_address'] = array(
  'retrieve' => array(
          'help' => 'Retrieve required fields for each Country',
          'callback' => '_hd_get_address_resource',
          'file' => array('type' => 'inc', 'module' => 'hd_endpoint', 'name' => 'resources/address'),
          'access callback' => 'services_access_menu',
          //'access arguments' => array('update'),
          //'access arguments append' => TRUE,
          'args' => array(
            array(
              'name' => 'country',
              'type' => 'string',
              'description' => '2 char country string',
              'source' => array('path' => 0),
              'optional' => FALSE,
            ),
          ),
        ),
  );

  return $resource;
}



